apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-r4se
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0046-tenant/tkrw-pr712-0075-0046-app/devfile-sample-r4se@sha256:757925b1d484df9bcc10aabd8f9415cd5c7bf9ad41c478ea7ccacaf86699f665
        name: my-nodejs
        resources: {}
status: {}
